"""complete analysis model

Revision ID: aa718aebe6fa
Revises: b1610411215d
Create Date: 2026-07-12 17:02:08.650148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa718aebe6fa'
down_revision: Union[str, Sequence[str], None] = 'b1610411215d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_clinical_documents',
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('clinical_document_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name='analysis_clinical_documents_analysis_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['clinical_document_id'], ['clinical_documents.id'], name='analysis_clinical_documents_clinical_document_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('analysis_id', 'clinical_document_id')
    )
    op.add_column('analyses', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('analyses', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('analyses', sa.Column('error_message', sa.Text(), nullable=True))
    # total_findings and the three severity counts are added with a server-side
    # default so this ALTER TABLE succeeds even if analyses already has rows in
    # some environment. The ORM model itself uses a Python-side default only,
    # matching this project's existing convention (see Analysis.status), but a
    # fresh ADD COLUMN ... NOT NULL needs a server default to be safe against
    # any pre-existing rows.
    op.add_column('analyses', sa.Column('total_findings', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('analyses', sa.Column('high_severity_findings', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('analyses', sa.Column('medium_severity_findings', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('analyses', sa.Column('low_severity_findings', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('analyses', sa.Column('provider', sa.String(), nullable=True))
    op.add_column('analyses', sa.Column('model_name', sa.String(), nullable=True))
    op.drop_column('analyses', 'processing_time_ms')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    Unlike the previous migration, this downgrade does not need to delete any
    rows to run safely. It only drops columns and the association table, and
    adds back processing_time_ms as nullable, none of which can violate a
    constraint regardless of existing data.

    It does lose data, though: started_at, completed_at, error_message,
    summary, the four finding counts, provider, model_name, and every
    analysis_clinical_documents link are discarded, since the legacy schema
    has no equivalent columns to hold them. This is an accepted, one-way loss
    of the fields this migration adds, not a constraint-safety workaround.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('processing_time_ms', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('analyses', 'model_name')
    op.drop_column('analyses', 'provider')
    op.drop_column('analyses', 'low_severity_findings')
    op.drop_column('analyses', 'medium_severity_findings')
    op.drop_column('analyses', 'high_severity_findings')
    op.drop_column('analyses', 'total_findings')
    op.drop_column('analyses', 'error_message')
    op.drop_column('analyses', 'completed_at')
    op.drop_column('analyses', 'started_at')
    op.drop_table('analysis_clinical_documents')
    # ### end Alembic commands ###
