"""restructure medication discrepancy model

Revision ID: b1610411215d
Revises: 239f8374acd3
Create Date: 2026-07-12 16:33:42.711787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1610411215d'
down_revision: Union[str, Sequence[str], None] = '239f8374acd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medication_discrepancies', sa.Column('medication_id', sa.Integer(), nullable=True))
    op.add_column('medication_discrepancies', sa.Column('medication_mention_id', sa.Integer(), nullable=True))
    op.add_column('medication_discrepancies', sa.Column('title', sa.String(), nullable=False))
    op.add_column('medication_discrepancies', sa.Column('expected_value', sa.String(), nullable=True))
    op.add_column('medication_discrepancies', sa.Column('observed_value', sa.String(), nullable=True))
    op.add_column('medication_discrepancies', sa.Column('resolution_status', sa.String(), nullable=False))
    op.alter_column('medication_discrepancies', 'severity',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_medication_discrepancies_medication_id'), 'medication_discrepancies', ['medication_id'], unique=False)
    op.create_index(op.f('ix_medication_discrepancies_medication_mention_id'), 'medication_discrepancies', ['medication_mention_id'], unique=False)
    op.drop_constraint(op.f('medication_discrepancies_source_document_a_id_fkey'), 'medication_discrepancies', type_='foreignkey')
    op.drop_constraint(op.f('medication_discrepancies_source_document_b_id_fkey'), 'medication_discrepancies', type_='foreignkey')
    op.create_foreign_key('medication_discrepancies_medication_mention_id_fkey', 'medication_discrepancies', 'medication_mentions', ['medication_mention_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('medication_discrepancies_medication_id_fkey', 'medication_discrepancies', 'medications', ['medication_id'], ['id'], ondelete='SET NULL')
    op.drop_column('medication_discrepancies', 'resolved')
    op.drop_column('medication_discrepancies', 'medication_name')
    op.drop_column('medication_discrepancies', 'source_document_b_id')
    op.drop_column('medication_discrepancies', 'normalized_name')
    op.drop_column('medication_discrepancies', 'source_document_a_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    The legacy schema required medication_name, resolved, source_document_a_id,
    and source_document_b_id as NOT NULL columns. Restoring them naively fails
    on any table that already has rows, since Postgres cannot add a NOT NULL
    column with no default to a non-empty table.

    medication_name and resolved have a defensible mapping from the current
    schema (medication_name from the referenced Medication or
    MedicationMention, resolved from resolution_status). That mapping does not
    matter in practice, though, because source_document_a_id and
    source_document_b_id do not. The current schema records a finding as an
    optional reference to a Medication and an optional reference to a single
    MedicationMention, not a pair of ClinicalDocuments being compared. There is
    no truthful way to recover which two documents a given finding used to
    reference, and inventing document ids would misrepresent real clinical
    evidence.

    Because at least one legacy NOT NULL column can never be populated
    truthfully for existing rows, this downgrade deletes all
    medication_discrepancies rows before restoring the legacy schema. This is
    a deliberate, documented loss of data: downgrading past this migration
    discards any reconciliation findings created under the current schema.
    Restoring the previous table structure is possible; restoring the data it
    used to hold is not.
    """
    # ### commands auto generated by Alembic - please adjust, and see the data
    # loss note in this function's docstring ###
    op.execute("DELETE FROM medication_discrepancies")

    op.add_column('medication_discrepancies', sa.Column('source_document_a_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('medication_discrepancies', sa.Column('normalized_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('medication_discrepancies', sa.Column('source_document_b_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('medication_discrepancies', sa.Column('medication_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('medication_discrepancies', sa.Column('resolved', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint('medication_discrepancies_medication_id_fkey', 'medication_discrepancies', type_='foreignkey')
    op.drop_constraint('medication_discrepancies_medication_mention_id_fkey', 'medication_discrepancies', type_='foreignkey')
    op.create_foreign_key(op.f('medication_discrepancies_source_document_b_id_fkey'), 'medication_discrepancies', 'clinical_documents', ['source_document_b_id'], ['id'])
    op.create_foreign_key(op.f('medication_discrepancies_source_document_a_id_fkey'), 'medication_discrepancies', 'clinical_documents', ['source_document_a_id'], ['id'])
    op.drop_index(op.f('ix_medication_discrepancies_medication_mention_id'), table_name='medication_discrepancies')
    op.drop_index(op.f('ix_medication_discrepancies_medication_id'), table_name='medication_discrepancies')
    op.alter_column('medication_discrepancies', 'severity',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('medication_discrepancies', 'resolution_status')
    op.drop_column('medication_discrepancies', 'observed_value')
    op.drop_column('medication_discrepancies', 'expected_value')
    op.drop_column('medication_discrepancies', 'title')
    op.drop_column('medication_discrepancies', 'medication_mention_id')
    op.drop_column('medication_discrepancies', 'medication_id')
    # ### end Alembic commands ###
