"""add storage metadata to clinical documents

Revision ID: c7dcd0163edd
Revises: 86d736611ffb
Create Date: 2026-08-03 18:57:49.304838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7dcd0163edd'
down_revision: Union[str, Sequence[str], None] = '86d736611ffb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Purely additive: all three columns are nullable, so every existing
    ClinicalDocument row (created before original files were ever stored
    anywhere - see Issue #58) is valid as-is with all three left null. No
    backfill is possible or attempted - the original file bytes for a
    pre-existing document were never persisted anywhere (disk or
    database), only its extracted raw_text, so there is nothing to
    retroactively store in S3/local storage for rows that predate this
    migration.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinical_documents', sa.Column('storage_key', sa.String(), nullable=True))
    op.add_column('clinical_documents', sa.Column('content_type', sa.String(), nullable=True))
    op.add_column('clinical_documents', sa.Column('file_size_bytes', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    Drops the three storage-metadata columns. Any object these rows
    pointed to remains in S3/local storage - this migration only touches
    Postgres, and deliberately does not attempt to delete storage objects
    as a side effect of a schema downgrade (a destructive, non-DDL action
    with no clean rollback of its own, out of place in a migration).
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clinical_documents', 'file_size_bytes')
    op.drop_column('clinical_documents', 'content_type')
    op.drop_column('clinical_documents', 'storage_key')
    # ### end Alembic commands ###
