"""add discrepancy resolution audit trail

Revision ID: d9346397f3b5
Revises: 3ef685b18302
Create Date: 2026-08-01 15:16:11.062707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9346397f3b5'
down_revision: Union[str, Sequence[str], None] = '3ef685b18302'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Purely additive: all four columns are nullable, so every existing
    MedicationDiscrepancy row (necessarily "open", since resolving one is
    what this migration makes possible for the first time) is valid as-is
    with all four left null; no backfill needed, no downgrade data loss.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medication_discrepancies', sa.Column('resolution_action', sa.String(), nullable=True))
    op.add_column('medication_discrepancies', sa.Column('resolved_by_user_id', sa.Integer(), nullable=True))
    op.add_column('medication_discrepancies', sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('medication_discrepancies', sa.Column('resolution_note', sa.Text(), nullable=True))
    op.create_index(op.f('ix_medication_discrepancies_resolved_by_user_id'), 'medication_discrepancies', ['resolved_by_user_id'], unique=False)
    op.create_foreign_key('medication_discrepancies_resolved_by_user_id_fkey', 'medication_discrepancies', 'users', ['resolved_by_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    Drops resolution data (which discrepancies were accepted/dismissed, by
    whom, when, and any note) along with the columns, a real, if smaller,
    loss of history, since there is nowhere else that state lives once
    these columns are removed.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('medication_discrepancies_resolved_by_user_id_fkey', 'medication_discrepancies', type_='foreignkey')
    op.drop_index(op.f('ix_medication_discrepancies_resolved_by_user_id'), table_name='medication_discrepancies')
    op.drop_column('medication_discrepancies', 'resolution_note')
    op.drop_column('medication_discrepancies', 'resolved_at')
    op.drop_column('medication_discrepancies', 'resolved_by_user_id')
    op.drop_column('medication_discrepancies', 'resolution_action')
    # ### end Alembic commands ###
